apiVersion: v1
kind: ConfigMap
metadata:
  name: aggregator-config
data:
  application.properties: |
    spring.application.name=aggregation-microservice
    server.port=8082
    temperature.unit=K
    temperature.url=http://temperature-service:8080/sensor/temp
    humidity.url=http://humidity-service:8081/sensor/humidity
